### ISSUE TITLE
Are any files missing?

### ISSUE THREAD

**Issue by RHEPI** [xl-tang3/UAUDeblur#1]
**Is the w.moat file missing for the line w_mat = scio.loadmat(' w.moat ') in the UaUDeblur_demo.py file? If not, could you please provide the file for learning?**

**Comment by xl-tang3** [comment]
Sorry for the confusion. The w.mat file is the simulated true residual that was previously used to test and tune the model parameter. It's no longer necessary for the fixed model so I've deleted the relevant variable and statements in the updated version.

**Comment by chunzizhu** [comment]
Where is the supplementary material for this paper?

**Comment by xl-tang01** [comment]
Updated in the repository.

**Comment by xl-tang3** [comment]
> Where is the supplementary material for this paper?

Updated in the repository.

**Comment by chunzizhu** [comment]
Is UaUDeblur_demo.py code used for training? Would it be convenient to publish the code for the test?

**Comment by ironman0086** [comment]
In debugging the file "UaUDeblur_demo.py", there is a error:
self.img_est_np = torch_to_np(self.img_est_torch).squeeze()
AttributeError: 'DeepResPrior' object has no attribute 'img_est_torch'
How could I revise this error?

**Comment by xl-tang3** [comment]
` line 140 'self.img_est_torch = torch.real(torch.fft.irfft2(torch.fft.rfft2(self.img_out_torch) * self.PSF))'`

Did you have declared a new variable 'img_est_torch' or comment out the line 140?
There's literally no attribute 'img_est_torch' in the latest version.

**Comment by ironman0086** [comment]
李付谦已收到。

**Comment by Marsbegi** [comment]
Hello, when I run UaUDeblur_demo.py according to the readme file, there is a problem of inconsistent dimensions. I found that the dimensions of the variables self.img_est_torch and self.img_blurred_torch are inconsistent when calculating mse.
How could I revise this error

**Comment by ironman0086** [comment]
李付谦已收到。

**Comment by xl-tang01** [comment]
> Hello, when I run UaUDeblur_demo.py according to the readme file, there is a problem of inconsistent dimensions. I found that the dimensions of the variables self.img_est_torch and self.img_blurred_torch are inconsistent when calculating mse.
> How could I revise this error



> Hello, when I run UaUDeblur_demo.py according to the readme file, there is a problem of inconsistent dimensions. I found that the dimensions of the variables self.img_est_torch and self.img_blurred_torch are inconsistent when calculating mse.
> How could I revise this error

It’s been noticed that many attempts have ended up with the same issue. To the best of my knowledge, it is concerned with the FFT transformation on line 139 since the experiment is implemented on
** PyTorch 1.10.1**, which is an old version.

**Comment by xl-tang01** [comment]
****

**Comment by xl-tang01** [comment]
> Hello, when I run UaUDeblur_demo.py according to the readme file, there is a problem of inconsistent dimensions. I found that the dimensions of the variables self.img_est_torch and self.img_blurred_torch are inconsistent when calculating mse. How could I revise this error
> 
> It’s been noticed that many attempts have ended up with the same issue. To the best of my knowledge, it is concerned with the FFT transformation on line 139 since the experiment is implemented on **PyTorch 1.10.1**, which is an old version.

Therefore it’s recommended to try another version or find alternative functions for torch.fft.xxx

**Comment by xl-tang3** [comment]
> Hello, when I run UaUDeblur_demo.py according to the readme file, there is a problem of inconsistent dimensions. I found that the dimensions of the variables self.img_est_torch and self.img_blurred_torch are inconsistent when calculating mse.
> How could I revise this error

It’s been noticed that many attempts have ended up with the same issue. To the best of my knowledge, it is concerned with the FFT transformation on line 139 since the experiment is implemented on **PyTorch 1.10.1**, which is an old version. Therefore, it’s recommended to try another version or find alternative functions for torch.fft.xxx.

**Comment by Marsbegi** [comment]
I get it.Thanks for your reply.



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 29, 2023 23:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xl-tang01/UAUDeblur] Are any files missing? (Issue #1)




  
Hello, when I run UaUDeblur_demo.py according to the readme file, there is a problem of inconsistent dimensions. I found that the dimensions of the variables self.img_est_torch and self.img_blurred_torch are inconsistent when calculating mse.
 How could I revise this error
   
Hello, when I run UaUDeblur_demo.py according to the readme file, there is a problem of inconsistent dimensions. I found that the dimensions of the variables self.img_est_torch and self.img_blurred_torch are inconsistent when calculating mse.
 How could I revise this error
  
It’s been noticed that many attempts have ended up with the same issue. To the best of my knowledge, it is concerned with the FFT transformation on line 139 since the experiment is implemented on
 ** PyTorch 1.10.1**, which is an old version.

**Comment by ironman0086** [comment]
李付谦已收到。
